---
version: '3.6'

services:
  gitlab:
    restart: always
    image: gitlab/gitlab-ce:15.9.8-ce.0
    hostname: gitlab
    ports:
      - "80:80"
      - "2222:2222"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://10.0.0.102'
        gitlab_rails['initial_root_password'] = "C1sco12345"
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['initial_shared_runners_registration_token'] = "sandboxrunners"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-data:/var/opt/gitlab
    extra_hosts:
      - "student-vm:10.0.0.102"

  runner1:
    restart: always
    image: gitlab/gitlab-runner:v15.9.1
    environment:
      - REGISTRATION_TOKEN=sandboxrunners
      - RUNNER_NAME=runner1
      - RUNNER_EXECUTOR=docker
      - CI_SERVER_URL=http://10.0.0.102
      - CLONE_URL=http://10.0.0.102
      - REGISTER_NON_INTERACTIVE=true
      - DOCKER_IMAGE=alpine
      - DOCKER_PULL_POLICY=if-not-present
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "student-vm:10.0.0.102"

volumes:
  gitlab-config:
    driver: local
  gitlab-data:
    driver: local

networks:
  default:
    name: lab-network
    driver: bridge
